sparkmaster:
  image: birgerk/apache-spark
  ports:
    - 4040:4040
    - 7077:7077
    - 8080:8080
  environment:
    SPARK_ROLE: master

sparkslave1:
  image: birgerk/apache-spark
  entrypoint: dockerize -wait tcp://sparkmaster:7077 -timeout 240s /sbin/my_init
  ports:
    - 8081:8081
  links:
    - sparkmaster
  environment:
    SPARK_MASTER: sparkmaster
    SPARK_ROLE: slave

sparkslave2:
  image: birgerk/apache-spark
  entrypoint: dockerize -wait tcp://sparkmaster:7077 -timeout 240s /sbin/my_init
  ports:
    - 8091:8081
  links:
    - sparkmaster
  environment:
    SPARK_MASTER: sparkmaster
    SPARK_ROLE: slave
